In [6]:
import pandas as pd
import numpy as np
from kmodes.kmodes import KModes
from kmodes.kprototypes import KPrototypes


#### Load Cleaned df from notebook#2

In [2]:
jewelry_df = pd.read_pickle('jewelry_df_clean.pkl')

In [3]:
jewelry_df.head()

category_path                                        description  \
0  Jewelry, Anklet  If yellow is your color this is perfect! \nA g...   
1  Jewelry, Anklet  Blue Angelite and Pink Cats eye beads with ste...   
2  Jewelry, Anklet  Add some playful, whimsical, and quirky person...   
3  Jewelry, Anklet  ♥100 % HAND WOVEN IN THAILAND \nThis is hand w...   
4  Jewelry, Anklet  ---AVENTURENE BEADS\n--HANDCRAFTED ANKLET\n--S...   

     ending_tsz  featured_rank  is_customizable  is_digital  is_supply  \
0  1.567639e+09         9999.0                0           0          0   
1  1.567639e+09         9999.0                0           0          0   
2  1.567640e+09         9999.0                0           0          0   
3  1.567640e+09         9999.0                0           0          0   
4  1.567640e+09           31.0                0           0          0   

   listing_id                                          materials non_taxable  \
0   230410899  Yellow glass czech beads, Bali style sterling ...       False   
1   230523456  Blue angelite beads, Pink cats eye beads, Ster...       False   
2   507888572       silver plated chain, Tassels, lobster clasps        True   
3   624383020                           waxed cord, stone, brass       False   
4   580563099             CHAIN, AVENTURENE BEADS, LOBSTER CLASP       False   

   ...                                               tags  \
0  ...  Beach Ankle Jewelry, Precious Elementz, Flower...   
1  ...  Beach Ankle Jewelry, Her ankle Jewelry, Girlfr...   
2  ...  a creative introvert, anklet, boho jewelry, Su...   
3  ...  lapis, Stone Anklets, Beaded Anklets, Woven An...   
4  ...  AVENTURENE BEADS, SILVER COLOR CHAIN, 11 INCH ...   

                    taxonomy_path  \
0  Jewelry, Body Jewelry, Anklets   
1  Jewelry, Body Jewelry, Anklets   
2  Jewelry, Body Jewelry, Anklets   
3  Jewelry, Body Jewelry, Anklets   
4  Jewelry, Body Jewelry, Anklets   

                                               title  used_manufacturer  \
0  Flower Anklet - Womens Beach Anklets - Yellow ...                  0   
1  Pink Beaded Anklet - Blue Ankle Bracelet - Bea...                  0   
2  Gypsy Tassel Anklet - Boho Anklet - Whimsical ...                  0   
3  Beaded Anklets Woven Anklets Lapis Woven Brass...                  0   
4                            CHAIN AVENTURENE ANKLET                  0   

      user_id views      when_made who_made price_usd  jewelry_catg  
0  64208725.0  11.0       standard    i_did     24.95        anklet  
1  64208725.0  18.0       standard    i_did     29.95        anklet  
2  46216365.0  48.0  made_to_order    i_did     10.00        anklet  
3   8527257.0  34.0       standard    i_did      8.00        anklet  
4  23040028.0  22.0        vintage    i_did     18.00        anklet  

[5 rows x 26 columns]

In [72]:
jewelry_df.tags.value_counts()

                                                                                                                                                                                                                                                     17637
pendant, silver pendant, Amber, Amber pendant, Amber silver pendant, brown pendant                                                                                                                                                                     130
dog, pet, animal, decoration, gift, present, sculpture, art, craft, jewelery, pendant, keyring, keychain                                                                                                                                               124
jewelry, gift, quadruple pets, dog, photojewelry, custom gift, jewelry on order, earrings, necklace, collection, box, set, dog lovers                                                                                                                  

In [8]:
X = jewelry_df.copy()

#### Data Prep for clustering 
Drop columns - End Date, Description, Listing ID, Title, User ID, Featured Rank, Is Digital, Is Supply, Non Taxable, Recipient, Used Manufacturer

In [17]:
X = X.drop(columns=['description', 'ending_tsz', 'listing_id', 'title','user_id'])
X= X.drop(columns=['jewelry_catg'])

In [21]:
X.head()

category_path  featured_rank  is_customizable  is_digital  is_supply  \
0  Jewelry, Anklet         9999.0                0           0          0   
1  Jewelry, Anklet         9999.0                0           0          0   
2  Jewelry, Anklet         9999.0                0           0          0   
3  Jewelry, Anklet         9999.0                0           0          0   
4  Jewelry, Anklet           31.0                0           0          0   

                                           materials non_taxable  \
0  Yellow glass czech beads, Bali style sterling ...       False   
1  Blue angelite beads, Pink cats eye beads, Ster...       False   
2       silver plated chain, Tassels, lobster clasps        True   
3                           waxed cord, stone, brass       False   
4             CHAIN, AVENTURENE BEADS, LOBSTER CLASP       False   

   num_favorers      occasion  processing_max  processing_min  quantity  \
0           2.0          None             2.0             1.0       1.0   
1           1.0          None             2.0             1.0       1.0   
2           7.0          None             3.0             1.0       3.0   
3           3.0  thanksgiving             3.0             1.0       5.0   
4           2.0          None             3.0             1.0       1.0   

  recipient                                               tags  \
0       any  Beach Ankle Jewelry, Precious Elementz, Flower...   
1       any  Beach Ankle Jewelry, Her ankle Jewelry, Girlfr...   
2       any  a creative introvert, anklet, boho jewelry, Su...   
3     women  lapis, Stone Anklets, Beaded Anklets, Woven An...   
4       any  AVENTURENE BEADS, SILVER COLOR CHAIN, 11 INCH ...   

                    taxonomy_path  used_manufacturer  views      when_made  \
0  Jewelry, Body Jewelry, Anklets                  0   11.0       standard   
1  Jewelry, Body Jewelry, Anklets                  0   18.0       standard   
2  Jewelry, Body Jewelry, Anklets                  0   48.0  made_to_order   
3  Jewelry, Body Jewelry, Anklets                  0   34.0       standard   
4  Jewelry, Body Jewelry, Anklets                  0   22.0        vintage   

  who_made  price_usd  
0    i_did      24.95  
1    i_did      29.95  
2    i_did      10.00  
3    i_did       8.00  
4    i_did      18.00

In [73]:
#Drop more columns
#1. featured_rank
#2. is_digital
#3. is_supply
#4. non_taxable
#5. recipient
#6. used_manufacturer
X = X.drop(columns=['featured_rank','is_digital','is_supply','non_taxable','recipient','used_manufacturer'])

In [74]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311047 entries, 0 to 311046
Data columns (total 14 columns):
category_path      311047 non-null object
is_customizable    311047 non-null int64
materials          311047 non-null object
num_favorers       311047 non-null float64
occasion           311047 non-null object
processing_max     311047 non-null float64
processing_min     311047 non-null float64
quantity           311047 non-null float64
tags               311047 non-null object
taxonomy_path      311047 non-null object
views              311047 non-null float64
when_made          311047 non-null object
who_made           311047 non-null object
price_usd          311047 non-null float64
dtypes: float64(6), int64(1), object(7)
memory usage: 33.2+ MB


#### Sample DataFrame to test clustering algorithm

In [75]:
X_test = X.sample(frac=0.2)

In [82]:
# X_test = X_test.drop(columns=['category_path'])
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62209 entries, 151842 to 15653
Data columns (total 13 columns):
is_customizable    62209 non-null int64
materials          62209 non-null object
num_favorers       62209 non-null float64
occasion           62209 non-null object
processing_max     62209 non-null float64
processing_min     62209 non-null float64
quantity           62209 non-null float64
tags               62209 non-null object
taxonomy_path      62209 non-null object
views              62209 non-null float64
when_made          62209 non-null object
who_made           62209 non-null object
price_usd          62209 non-null float64
dtypes: float64(6), int64(1), object(6)
memory usage: 6.6+ MB


In [79]:
X_test.head()

is_customizable                                          materials  \
151842                0  bezels, nickel free bezels, Americana cabochon...   
261700                0                         turquoise, sterling silver   
264540                0                                    Stainless steel   
144297                1                           Silver, Polyester, Brass   
252974                1                              sterling silver, silk   

        num_favorers occasion  processing_max  processing_min  quantity  \
151842           8.0     None             3.0             1.0       4.0   
261700          11.0     None             1.0             1.0       1.0   
264540           8.0     None             1.0             1.0       1.0   
144297           5.0     None             2.0             1.0      20.0   
252974          46.0     None            10.0             5.0       2.0   

                                                     tags  \
151842  Fourth of July studs, patriotic accessorie, pa...   
261700                                                      
264540  Over Lap Tear Drop, Stainless Tear Drops, VTG ...   
144297  bunny brooch, discobunny, rabbit brooch, disco...   
252974  necklace, pendant, sterling silver, silver, bu...   

                                    taxonomy_path  views      when_made  \
151842           Jewelry, Earrings, Stud Earrings  514.0       standard   
261700            Jewelry, Rings, Solitaire Rings   34.0        vintage   
264540            Jewelry, Rings, Statement Rings   49.0        vintage   
144297  Jewelry, Brooches, Pins & Clips, Brooches   25.0       standard   
252974               Jewelry, Necklaces, Pendants  359.0  made_to_order   

            who_made  price_usd  
151842         i_did      8.000  
261700  someone_else     49.750  
264540  someone_else     24.990  
144297         i_did      6.027  
252974         i_did     67.320

In [81]:
X_test.to_pickle('test_df.pkl')

### K Prototype for clustering numeric + categorical fields 

(try 5 clusters)

In [83]:
kp = KPrototypes(n_clusters=5, init='Huang', n_init=1, verbose=True, n_jobs = -1)

kp.fit_predict(X_test, categorical = [0,1,3,7,8,10,11])

# print(kp.cluster_centroids_)
# print(kp.labels_)

array([2, 2, 2, ..., 2, 2, 2], dtype=uint16)

In [84]:
pd.Series(kp.labels_).value_counts()
kp.

2    61237
4      709
0      203
1       54
3        6
dtype: int64

In [85]:
for elem in zip(kp.cluster_centroids_[0], kp.cluster_centroids_[1]):
    print(elem)
    print('******\n\n')

(array([4.23596059e+01, 5.05418719e+00, 2.91625616e+00, 2.10837438e+00,
       4.59847291e+02, 9.12215483e+03]), array(['0', 'Diamond, Gold', 'None',
       'Engagement, Diamond, Ring, Wedding, Round',
       'Jewelry, Rings, Wedding & Engagement, Engagement Rings',
       'vintage', 'i_did'], dtype='<U219'))
******


(array([2.77061111e+03, 6.87037037e+00, 3.83333333e+00, 5.69444444e+01,
       2.79427407e+04, 2.27419787e+02]), array(['1', '', 'None',
       'ANKLET, BRACELET, GOLD, BEACH, FESTIVAL, GYPSY, CHAIN ANKLE PIECE, BOHEMIAN, ANKLE JEWELRY, white, barefoot sandal, Boho chic, Wedding',
       'Jewelry, Body Jewelry, Anklets', 'made_to_order', 'i_did'],
      dtype='<U219'))
******


(array([ 21.78493395,   3.67919722,   1.93381452,  12.58474452,
       134.32975162, 112.35839612]), array(['0', '', 'None', '', 'Jewelry, Brooches, Pins & Clips, Brooches',
       'standard', 'i_did'], dtype='<U219'))
******


(array([4.02983333e+03, 6.33333333e+00, 4.33333333e+00, 4.20000000e+01,